# Generated by Django 6.1.1 on 2026-09-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='KKA Oil Mill', max_length=150)),
                ('manufacturer_name', models.CharField(default='Deepam Oils Mill', max_length=150)),
                ('address', models.TextField(blank=True)),
                ('fssai_number', models.CharField(blank=True, max_length=50)),
                ('about_text', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('phone1', models.CharField(blank=True, max_length=30)),
                ('phone2', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('show_facebook', models.BooleanField(default=True)),
                ('show_instagram', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tamil_name', models.CharField(blank=True, max_length=150)),
                ('pack_size', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('show_price', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
